### ISSUE TITLE
大神你好，vip土豆已经消失，另外能否增加其他视频网站vip

### ISSUE THREAD

**Issue by xiaoliu2012** [loyingEcu/cu#1]
大神你好，vip土豆已经消失，另外能否增加其他视频网站vip，比如mgtv，pptv（http://vip.pptv.com/）等。http://v.m3l.net/这个网站可能会有所帮助。我也只是提提意见，具体还看大神自己安排。万分感激！

**Comment by loyingEcu** [comment]
芒果TV pptv 很早以前就搞定了

没想过有人会给我留言 一直没注意
